### ISSUE TITLE
updating an item in the cursor

### ISSUE THREAD

**Issue by muyiwamc2** [jakewins/neo4jdb-python#12]
Hi,
I was wondering if I update a property of a node returned from a cursor will it persist after a call to connection.commit?
Olu

**Comment by jakewins** [comment]
No - the objects you get from the cursor are completely detached. This is by design, in order to keep this library light weight and simple. For that kind of stuff (eg. "live" objects), I'd recommend building a library on top of this one, like a graph mapping library :)
